/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AppBackupLister helps list AppBackups.
// All objects returned here must be treated as read-only.
type AppBackupLister interface {
	// List lists all AppBackups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.AppBackup, err error)
	// AppBackups returns an object that can list and get AppBackups.
	AppBackups(namespace string) AppBackupNamespaceLister
	AppBackupListerExpansion
}

// appBackupLister implements the AppBackupLister interface.
type appBackupLister struct {
	listers.ResourceIndexer[*disasterv1.AppBackup]
}

// NewAppBackupLister returns a new AppBackupLister.
func NewAppBackupLister(indexer cache.Indexer) AppBackupLister {
	return &appBackupLister{listers.New[*disasterv1.AppBackup](indexer, disasterv1.Resource("appbackup"))}
}

// AppBackups returns an object that can list and get AppBackups.
func (s *appBackupLister) AppBackups(namespace string) AppBackupNamespaceLister {
	return appBackupNamespaceLister{listers.NewNamespaced[*disasterv1.AppBackup](s.ResourceIndexer, namespace)}
}

// AppBackupNamespaceLister helps list and get AppBackups.
// All objects returned here must be treated as read-only.
type AppBackupNamespaceLister interface {
	// List lists all AppBackups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.AppBackup, err error)
	// Get retrieves the AppBackup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.AppBackup, error)
	AppBackupNamespaceListerExpansion
}

// appBackupNamespaceLister implements the AppBackupNamespaceLister
// interface.
type appBackupNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.AppBackup]
}
