/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AppRestoreLister helps list AppRestores.
// All objects returned here must be treated as read-only.
type AppRestoreLister interface {
	// List lists all AppRestores in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.AppRestore, err error)
	// AppRestores returns an object that can list and get AppRestores.
	AppRestores(namespace string) AppRestoreNamespaceLister
	AppRestoreListerExpansion
}

// appRestoreLister implements the AppRestoreLister interface.
type appRestoreLister struct {
	listers.ResourceIndexer[*disasterv1.AppRestore]
}

// NewAppRestoreLister returns a new AppRestoreLister.
func NewAppRestoreLister(indexer cache.Indexer) AppRestoreLister {
	return &appRestoreLister{listers.New[*disasterv1.AppRestore](indexer, disasterv1.Resource("apprestore"))}
}

// AppRestores returns an object that can list and get AppRestores.
func (s *appRestoreLister) AppRestores(namespace string) AppRestoreNamespaceLister {
	return appRestoreNamespaceLister{listers.NewNamespaced[*disasterv1.AppRestore](s.ResourceIndexer, namespace)}
}

// AppRestoreNamespaceLister helps list and get AppRestores.
// All objects returned here must be treated as read-only.
type AppRestoreNamespaceLister interface {
	// List lists all AppRestores in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.AppRestore, err error)
	// Get retrieves the AppRestore from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.AppRestore, error)
	AppRestoreNamespaceListerExpansion
}

// appRestoreNamespaceLister implements the AppRestoreNamespaceLister
// interface.
type appRestoreNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.AppRestore]
}
