/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BackupPolicyLister helps list BackupPolicies.
// All objects returned here must be treated as read-only.
type BackupPolicyLister interface {
	// List lists all BackupPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.BackupPolicy, err error)
	// BackupPolicies returns an object that can list and get BackupPolicies.
	BackupPolicies(namespace string) BackupPolicyNamespaceLister
	BackupPolicyListerExpansion
}

// backupPolicyLister implements the BackupPolicyLister interface.
type backupPolicyLister struct {
	listers.ResourceIndexer[*disasterv1.BackupPolicy]
}

// NewBackupPolicyLister returns a new BackupPolicyLister.
func NewBackupPolicyLister(indexer cache.Indexer) BackupPolicyLister {
	return &backupPolicyLister{listers.New[*disasterv1.BackupPolicy](indexer, disasterv1.Resource("backuppolicy"))}
}

// BackupPolicies returns an object that can list and get BackupPolicies.
func (s *backupPolicyLister) BackupPolicies(namespace string) BackupPolicyNamespaceLister {
	return backupPolicyNamespaceLister{listers.NewNamespaced[*disasterv1.BackupPolicy](s.ResourceIndexer, namespace)}
}

// BackupPolicyNamespaceLister helps list and get BackupPolicies.
// All objects returned here must be treated as read-only.
type BackupPolicyNamespaceLister interface {
	// List lists all BackupPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.BackupPolicy, err error)
	// Get retrieves the BackupPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.BackupPolicy, error)
	BackupPolicyNamespaceListerExpansion
}

// backupPolicyNamespaceLister implements the BackupPolicyNamespaceLister
// interface.
type backupPolicyNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.BackupPolicy]
}
