/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BackupRestoreStatisticsLister helps list BackupRestoreStatisticses.
// All objects returned here must be treated as read-only.
type BackupRestoreStatisticsLister interface {
	// List lists all BackupRestoreStatisticses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.BackupRestoreStatistics, err error)
	// BackupRestoreStatisticses returns an object that can list and get BackupRestoreStatisticses.
	BackupRestoreStatisticses(namespace string) BackupRestoreStatisticsNamespaceLister
	BackupRestoreStatisticsListerExpansion
}

// backupRestoreStatisticsLister implements the BackupRestoreStatisticsLister interface.
type backupRestoreStatisticsLister struct {
	listers.ResourceIndexer[*disasterv1.BackupRestoreStatistics]
}

// NewBackupRestoreStatisticsLister returns a new BackupRestoreStatisticsLister.
func NewBackupRestoreStatisticsLister(indexer cache.Indexer) BackupRestoreStatisticsLister {
	return &backupRestoreStatisticsLister{listers.New[*disasterv1.BackupRestoreStatistics](indexer, disasterv1.Resource("backuprestorestatistics"))}
}

// BackupRestoreStatisticses returns an object that can list and get BackupRestoreStatisticses.
func (s *backupRestoreStatisticsLister) BackupRestoreStatisticses(namespace string) BackupRestoreStatisticsNamespaceLister {
	return backupRestoreStatisticsNamespaceLister{listers.NewNamespaced[*disasterv1.BackupRestoreStatistics](s.ResourceIndexer, namespace)}
}

// BackupRestoreStatisticsNamespaceLister helps list and get BackupRestoreStatisticses.
// All objects returned here must be treated as read-only.
type BackupRestoreStatisticsNamespaceLister interface {
	// List lists all BackupRestoreStatisticses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.BackupRestoreStatistics, err error)
	// Get retrieves the BackupRestoreStatistics from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.BackupRestoreStatistics, error)
	BackupRestoreStatisticsNamespaceListerExpansion
}

// backupRestoreStatisticsNamespaceLister implements the BackupRestoreStatisticsNamespaceLister
// interface.
type backupRestoreStatisticsNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.BackupRestoreStatistics]
}
