/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DataSyncLister helps list DataSyncs.
// All objects returned here must be treated as read-only.
type DataSyncLister interface {
	// List lists all DataSyncs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DataSync, err error)
	// DataSyncs returns an object that can list and get DataSyncs.
	DataSyncs(namespace string) DataSyncNamespaceLister
	DataSyncListerExpansion
}

// dataSyncLister implements the DataSyncLister interface.
type dataSyncLister struct {
	listers.ResourceIndexer[*disasterv1.DataSync]
}

// NewDataSyncLister returns a new DataSyncLister.
func NewDataSyncLister(indexer cache.Indexer) DataSyncLister {
	return &dataSyncLister{listers.New[*disasterv1.DataSync](indexer, disasterv1.Resource("datasync"))}
}

// DataSyncs returns an object that can list and get DataSyncs.
func (s *dataSyncLister) DataSyncs(namespace string) DataSyncNamespaceLister {
	return dataSyncNamespaceLister{listers.NewNamespaced[*disasterv1.DataSync](s.ResourceIndexer, namespace)}
}

// DataSyncNamespaceLister helps list and get DataSyncs.
// All objects returned here must be treated as read-only.
type DataSyncNamespaceLister interface {
	// List lists all DataSyncs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DataSync, err error)
	// Get retrieves the DataSync from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DataSync, error)
	DataSyncNamespaceListerExpansion
}

// dataSyncNamespaceLister implements the DataSyncNamespaceLister
// interface.
type dataSyncNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DataSync]
}
