/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterJobLister helps list DisasterJobs.
// All objects returned here must be treated as read-only.
type DisasterJobLister interface {
	// List lists all DisasterJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterJob, err error)
	// DisasterJobs returns an object that can list and get DisasterJobs.
	DisasterJobs(namespace string) DisasterJobNamespaceLister
	DisasterJobListerExpansion
}

// disasterJobLister implements the DisasterJobLister interface.
type disasterJobLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterJob]
}

// NewDisasterJobLister returns a new DisasterJobLister.
func NewDisasterJobLister(indexer cache.Indexer) DisasterJobLister {
	return &disasterJobLister{listers.New[*disasterv1.DisasterJob](indexer, disasterv1.Resource("disasterjob"))}
}

// DisasterJobs returns an object that can list and get DisasterJobs.
func (s *disasterJobLister) DisasterJobs(namespace string) DisasterJobNamespaceLister {
	return disasterJobNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterJob](s.ResourceIndexer, namespace)}
}

// DisasterJobNamespaceLister helps list and get DisasterJobs.
// All objects returned here must be treated as read-only.
type DisasterJobNamespaceLister interface {
	// List lists all DisasterJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterJob, err error)
	// Get retrieves the DisasterJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterJob, error)
	DisasterJobNamespaceListerExpansion
}

// disasterJobNamespaceLister implements the DisasterJobNamespaceLister
// interface.
type disasterJobNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterJob]
}
