/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterConfigLister helps list DisasterConfigs.
// All objects returned here must be treated as read-only.
type DisasterConfigLister interface {
	// List lists all DisasterConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterConfig, err error)
	// Get retrieves the DisasterConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterConfig, error)
	DisasterConfigListerExpansion
}

// disasterConfigLister implements the DisasterConfigLister interface.
type disasterConfigLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterConfig]
}

// NewDisasterConfigLister returns a new DisasterConfigLister.
func NewDisasterConfigLister(indexer cache.Indexer) DisasterConfigLister {
	return &disasterConfigLister{listers.New[*disasterv1.DisasterConfig](indexer, disasterv1.Resource("disasterconfig"))}
}
