/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterGroupLister helps list DisasterGroups.
// All objects returned here must be treated as read-only.
type DisasterGroupLister interface {
	// List lists all DisasterGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterGroup, err error)
	// DisasterGroups returns an object that can list and get DisasterGroups.
	DisasterGroups(namespace string) DisasterGroupNamespaceLister
	DisasterGroupListerExpansion
}

// disasterGroupLister implements the DisasterGroupLister interface.
type disasterGroupLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterGroup]
}

// NewDisasterGroupLister returns a new DisasterGroupLister.
func NewDisasterGroupLister(indexer cache.Indexer) DisasterGroupLister {
	return &disasterGroupLister{listers.New[*disasterv1.DisasterGroup](indexer, disasterv1.Resource("disastergroup"))}
}

// DisasterGroups returns an object that can list and get DisasterGroups.
func (s *disasterGroupLister) DisasterGroups(namespace string) DisasterGroupNamespaceLister {
	return disasterGroupNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterGroup](s.ResourceIndexer, namespace)}
}

// DisasterGroupNamespaceLister helps list and get DisasterGroups.
// All objects returned here must be treated as read-only.
type DisasterGroupNamespaceLister interface {
	// List lists all DisasterGroups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterGroup, err error)
	// Get retrieves the DisasterGroup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterGroup, error)
	DisasterGroupNamespaceListerExpansion
}

// disasterGroupNamespaceLister implements the DisasterGroupNamespaceLister
// interface.
type disasterGroupNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterGroup]
}
