/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterBackupLister helps list DisasterBackups.
// All objects returned here must be treated as read-only.
type DisasterBackupLister interface {
	// List lists all DisasterBackups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterBackup, err error)
	// DisasterBackups returns an object that can list and get DisasterBackups.
	DisasterBackups(namespace string) DisasterBackupNamespaceLister
	DisasterBackupListerExpansion
}

// disasterBackupLister implements the DisasterBackupLister interface.
type disasterBackupLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterBackup]
}

// NewDisasterBackupLister returns a new DisasterBackupLister.
func NewDisasterBackupLister(indexer cache.Indexer) DisasterBackupLister {
	return &disasterBackupLister{listers.New[*disasterv1.DisasterBackup](indexer, disasterv1.Resource("disasterbackup"))}
}

// DisasterBackups returns an object that can list and get DisasterBackups.
func (s *disasterBackupLister) DisasterBackups(namespace string) DisasterBackupNamespaceLister {
	return disasterBackupNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterBackup](s.ResourceIndexer, namespace)}
}

// DisasterBackupNamespaceLister helps list and get DisasterBackups.
// All objects returned here must be treated as read-only.
type DisasterBackupNamespaceLister interface {
	// List lists all DisasterBackups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterBackup, err error)
	// Get retrieves the DisasterBackup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterBackup, error)
	DisasterBackupNamespaceListerExpansion
}

// disasterBackupNamespaceLister implements the DisasterBackupNamespaceLister
// interface.
type disasterBackupNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterBackup]
}
