/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterDrillLister helps list DisasterDrills.
// All objects returned here must be treated as read-only.
type DisasterDrillLister interface {
	// List lists all DisasterDrills in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterDrill, err error)
	// DisasterDrills returns an object that can list and get DisasterDrills.
	DisasterDrills(namespace string) DisasterDrillNamespaceLister
	DisasterDrillListerExpansion
}

// disasterDrillLister implements the DisasterDrillLister interface.
type disasterDrillLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterDrill]
}

// NewDisasterDrillLister returns a new DisasterDrillLister.
func NewDisasterDrillLister(indexer cache.Indexer) DisasterDrillLister {
	return &disasterDrillLister{listers.New[*disasterv1.DisasterDrill](indexer, disasterv1.Resource("disasterdrill"))}
}

// DisasterDrills returns an object that can list and get DisasterDrills.
func (s *disasterDrillLister) DisasterDrills(namespace string) DisasterDrillNamespaceLister {
	return disasterDrillNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterDrill](s.ResourceIndexer, namespace)}
}

// DisasterDrillNamespaceLister helps list and get DisasterDrills.
// All objects returned here must be treated as read-only.
type DisasterDrillNamespaceLister interface {
	// List lists all DisasterDrills in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterDrill, err error)
	// Get retrieves the DisasterDrill from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterDrill, error)
	DisasterDrillNamespaceListerExpansion
}

// disasterDrillNamespaceLister implements the DisasterDrillNamespaceLister
// interface.
type disasterDrillNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterDrill]
}
