/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterInstanceLister helps list DisasterInstances.
// All objects returned here must be treated as read-only.
type DisasterInstanceLister interface {
	// List lists all DisasterInstances in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterInstance, err error)
	// DisasterInstances returns an object that can list and get DisasterInstances.
	DisasterInstances(namespace string) DisasterInstanceNamespaceLister
	DisasterInstanceListerExpansion
}

// disasterInstanceLister implements the DisasterInstanceLister interface.
type disasterInstanceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterInstance]
}

// NewDisasterInstanceLister returns a new DisasterInstanceLister.
func NewDisasterInstanceLister(indexer cache.Indexer) DisasterInstanceLister {
	return &disasterInstanceLister{listers.New[*disasterv1.DisasterInstance](indexer, disasterv1.Resource("disasterinstance"))}
}

// DisasterInstances returns an object that can list and get DisasterInstances.
func (s *disasterInstanceLister) DisasterInstances(namespace string) DisasterInstanceNamespaceLister {
	return disasterInstanceNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterInstance](s.ResourceIndexer, namespace)}
}

// DisasterInstanceNamespaceLister helps list and get DisasterInstances.
// All objects returned here must be treated as read-only.
type DisasterInstanceNamespaceLister interface {
	// List lists all DisasterInstances in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterInstance, err error)
	// Get retrieves the DisasterInstance from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterInstance, error)
	DisasterInstanceNamespaceListerExpansion
}

// disasterInstanceNamespaceLister implements the DisasterInstanceNamespaceLister
// interface.
type disasterInstanceNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterInstance]
}
