/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterOperationLister helps list DisasterOperations.
// All objects returned here must be treated as read-only.
type DisasterOperationLister interface {
	// List lists all DisasterOperations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterOperation, err error)
	// DisasterOperations returns an object that can list and get DisasterOperations.
	DisasterOperations(namespace string) DisasterOperationNamespaceLister
	DisasterOperationListerExpansion
}

// disasterOperationLister implements the DisasterOperationLister interface.
type disasterOperationLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterOperation]
}

// NewDisasterOperationLister returns a new DisasterOperationLister.
func NewDisasterOperationLister(indexer cache.Indexer) DisasterOperationLister {
	return &disasterOperationLister{listers.New[*disasterv1.DisasterOperation](indexer, disasterv1.Resource("disasteroperation"))}
}

// DisasterOperations returns an object that can list and get DisasterOperations.
func (s *disasterOperationLister) DisasterOperations(namespace string) DisasterOperationNamespaceLister {
	return disasterOperationNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterOperation](s.ResourceIndexer, namespace)}
}

// DisasterOperationNamespaceLister helps list and get DisasterOperations.
// All objects returned here must be treated as read-only.
type DisasterOperationNamespaceLister interface {
	// List lists all DisasterOperations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterOperation, err error)
	// Get retrieves the DisasterOperation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterOperation, error)
	DisasterOperationNamespaceListerExpansion
}

// disasterOperationNamespaceLister implements the DisasterOperationNamespaceLister
// interface.
type disasterOperationNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterOperation]
}
