/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterPolicyLister helps list DisasterPolicies.
// All objects returned here must be treated as read-only.
type DisasterPolicyLister interface {
	// List lists all DisasterPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterPolicy, err error)
	// DisasterPolicies returns an object that can list and get DisasterPolicies.
	DisasterPolicies(namespace string) DisasterPolicyNamespaceLister
	DisasterPolicyListerExpansion
}

// disasterPolicyLister implements the DisasterPolicyLister interface.
type disasterPolicyLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterPolicy]
}

// NewDisasterPolicyLister returns a new DisasterPolicyLister.
func NewDisasterPolicyLister(indexer cache.Indexer) DisasterPolicyLister {
	return &disasterPolicyLister{listers.New[*disasterv1.DisasterPolicy](indexer, disasterv1.Resource("disasterpolicy"))}
}

// DisasterPolicies returns an object that can list and get DisasterPolicies.
func (s *disasterPolicyLister) DisasterPolicies(namespace string) DisasterPolicyNamespaceLister {
	return disasterPolicyNamespaceLister{listers.NewNamespaced[*disasterv1.DisasterPolicy](s.ResourceIndexer, namespace)}
}

// DisasterPolicyNamespaceLister helps list and get DisasterPolicies.
// All objects returned here must be treated as read-only.
type DisasterPolicyNamespaceLister interface {
	// List lists all DisasterPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.DisasterPolicy, err error)
	// Get retrieves the DisasterPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.DisasterPolicy, error)
	DisasterPolicyNamespaceListerExpansion
}

// disasterPolicyNamespaceLister implements the DisasterPolicyNamespaceLister
// interface.
type disasterPolicyNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.DisasterPolicy]
}
