/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// AppBackupListerExpansion allows custom methods to be added to
// AppBackupLister.
type AppBackupListerExpansion interface{}

// AppBackupNamespaceListerExpansion allows custom methods to be added to
// AppBackupNamespaceLister.
type AppBackupNamespaceListerExpansion interface{}

// AppRestoreListerExpansion allows custom methods to be added to
// AppRestoreLister.
type AppRestoreListerExpansion interface{}

// AppRestoreNamespaceListerExpansion allows custom methods to be added to
// AppRestoreNamespaceLister.
type AppRestoreNamespaceListerExpansion interface{}

// BackupPolicyListerExpansion allows custom methods to be added to
// BackupPolicyLister.
type BackupPolicyListerExpansion interface{}

// BackupPolicyNamespaceListerExpansion allows custom methods to be added to
// BackupPolicyNamespaceLister.
type BackupPolicyNamespaceListerExpansion interface{}

// BackupRestoreStatisticsListerExpansion allows custom methods to be added to
// BackupRestoreStatisticsLister.
type BackupRestoreStatisticsListerExpansion interface{}

// BackupRestoreStatisticsNamespaceListerExpansion allows custom methods to be added to
// BackupRestoreStatisticsNamespaceLister.
type BackupRestoreStatisticsNamespaceListerExpansion interface{}

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// DataSyncListerExpansion allows custom methods to be added to
// DataSyncLister.
type DataSyncListerExpansion interface{}

// DataSyncNamespaceListerExpansion allows custom methods to be added to
// DataSyncNamespaceLister.
type DataSyncNamespaceListerExpansion interface{}

// DisasterBackupListerExpansion allows custom methods to be added to
// DisasterBackupLister.
type DisasterBackupListerExpansion interface{}

// DisasterBackupNamespaceListerExpansion allows custom methods to be added to
// DisasterBackupNamespaceLister.
type DisasterBackupNamespaceListerExpansion interface{}

// DisasterConfigListerExpansion allows custom methods to be added to
// DisasterConfigLister.
type DisasterConfigListerExpansion interface{}

// DisasterDrillListerExpansion allows custom methods to be added to
// DisasterDrillLister.
type DisasterDrillListerExpansion interface{}

// DisasterDrillNamespaceListerExpansion allows custom methods to be added to
// DisasterDrillNamespaceLister.
type DisasterDrillNamespaceListerExpansion interface{}

// DisasterGroupListerExpansion allows custom methods to be added to
// DisasterGroupLister.
type DisasterGroupListerExpansion interface{}

// DisasterGroupNamespaceListerExpansion allows custom methods to be added to
// DisasterGroupNamespaceLister.
type DisasterGroupNamespaceListerExpansion interface{}

// DisasterInstanceListerExpansion allows custom methods to be added to
// DisasterInstanceLister.
type DisasterInstanceListerExpansion interface{}

// DisasterInstanceNamespaceListerExpansion allows custom methods to be added to
// DisasterInstanceNamespaceLister.
type DisasterInstanceNamespaceListerExpansion interface{}

// DisasterJobListerExpansion allows custom methods to be added to
// DisasterJobLister.
type DisasterJobListerExpansion interface{}

// DisasterJobNamespaceListerExpansion allows custom methods to be added to
// DisasterJobNamespaceLister.
type DisasterJobNamespaceListerExpansion interface{}

// DisasterOperationListerExpansion allows custom methods to be added to
// DisasterOperationLister.
type DisasterOperationListerExpansion interface{}

// DisasterOperationNamespaceListerExpansion allows custom methods to be added to
// DisasterOperationNamespaceLister.
type DisasterOperationNamespaceListerExpansion interface{}

// DisasterPolicyListerExpansion allows custom methods to be added to
// DisasterPolicyLister.
type DisasterPolicyListerExpansion interface{}

// DisasterPolicyNamespaceListerExpansion allows custom methods to be added to
// DisasterPolicyNamespaceLister.
type DisasterPolicyNamespaceListerExpansion interface{}

// ResourceSyncListerExpansion allows custom methods to be added to
// ResourceSyncLister.
type ResourceSyncListerExpansion interface{}

// ResourceSyncNamespaceListerExpansion allows custom methods to be added to
// ResourceSyncNamespaceLister.
type ResourceSyncNamespaceListerExpansion interface{}

// StorageRepositoryListerExpansion allows custom methods to be added to
// StorageRepositoryLister.
type StorageRepositoryListerExpansion interface{}

// StorageRepositoryNamespaceListerExpansion allows custom methods to be added to
// StorageRepositoryNamespaceLister.
type StorageRepositoryNamespaceListerExpansion interface{}
