/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ResourceSyncLister helps list ResourceSyncs.
// All objects returned here must be treated as read-only.
type ResourceSyncLister interface {
	// List lists all ResourceSyncs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.ResourceSync, err error)
	// ResourceSyncs returns an object that can list and get ResourceSyncs.
	ResourceSyncs(namespace string) ResourceSyncNamespaceLister
	ResourceSyncListerExpansion
}

// resourceSyncLister implements the ResourceSyncLister interface.
type resourceSyncLister struct {
	listers.ResourceIndexer[*disasterv1.ResourceSync]
}

// NewResourceSyncLister returns a new ResourceSyncLister.
func NewResourceSyncLister(indexer cache.Indexer) ResourceSyncLister {
	return &resourceSyncLister{listers.New[*disasterv1.ResourceSync](indexer, disasterv1.Resource("resourcesync"))}
}

// ResourceSyncs returns an object that can list and get ResourceSyncs.
func (s *resourceSyncLister) ResourceSyncs(namespace string) ResourceSyncNamespaceLister {
	return resourceSyncNamespaceLister{listers.NewNamespaced[*disasterv1.ResourceSync](s.ResourceIndexer, namespace)}
}

// ResourceSyncNamespaceLister helps list and get ResourceSyncs.
// All objects returned here must be treated as read-only.
type ResourceSyncNamespaceLister interface {
	// List lists all ResourceSyncs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.ResourceSync, err error)
	// Get retrieves the ResourceSync from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.ResourceSync, error)
	ResourceSyncNamespaceListerExpansion
}

// resourceSyncNamespaceLister implements the ResourceSyncNamespaceLister
// interface.
type resourceSyncNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.ResourceSync]
}
