/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// StorageRepositoryLister helps list StorageRepositories.
// All objects returned here must be treated as read-only.
type StorageRepositoryLister interface {
	// List lists all StorageRepositories in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.StorageRepository, err error)
	// StorageRepositories returns an object that can list and get StorageRepositories.
	StorageRepositories(namespace string) StorageRepositoryNamespaceLister
	StorageRepositoryListerExpansion
}

// storageRepositoryLister implements the StorageRepositoryLister interface.
type storageRepositoryLister struct {
	listers.ResourceIndexer[*disasterv1.StorageRepository]
}

// NewStorageRepositoryLister returns a new StorageRepositoryLister.
func NewStorageRepositoryLister(indexer cache.Indexer) StorageRepositoryLister {
	return &storageRepositoryLister{listers.New[*disasterv1.StorageRepository](indexer, disasterv1.Resource("storagerepository"))}
}

// StorageRepositories returns an object that can list and get StorageRepositories.
func (s *storageRepositoryLister) StorageRepositories(namespace string) StorageRepositoryNamespaceLister {
	return storageRepositoryNamespaceLister{listers.NewNamespaced[*disasterv1.StorageRepository](s.ResourceIndexer, namespace)}
}

// StorageRepositoryNamespaceLister helps list and get StorageRepositories.
// All objects returned here must be treated as read-only.
type StorageRepositoryNamespaceLister interface {
	// List lists all StorageRepositories in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*disasterv1.StorageRepository, err error)
	// Get retrieves the StorageRepository from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*disasterv1.StorageRepository, error)
	StorageRepositoryNamespaceListerExpansion
}

// storageRepositoryNamespaceLister implements the StorageRepositoryNamespaceLister
// interface.
type storageRepositoryNamespaceLister struct {
	listers.ResourceIndexer[*disasterv1.StorageRepository]
}
