//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	velerov1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppBackup) DeepCopyInto(out *AppBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppBackup.
func (in *AppBackup) DeepCopy() *AppBackup {
	if in == nil {
		return nil
	}
	out := new(AppBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppBackupList) DeepCopyInto(out *AppBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppBackupList.
func (in *AppBackupList) DeepCopy() *AppBackupList {
	if in == nil {
		return nil
	}
	out := new(AppBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppBackupSpec) DeepCopyInto(out *AppBackupSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.UseOwnerReferencesInBackup != nil {
		in, out := &in.UseOwnerReferencesInBackup, &out.UseOwnerReferencesInBackup
		*out = new(bool)
		**out = **in
	}
	if in.SkipImmediately != nil {
		in, out := &in.SkipImmediately, &out.SkipImmediately
		*out = new(bool)
		**out = **in
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(BackupAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppBackupSpec.
func (in *AppBackupSpec) DeepCopy() *AppBackupSpec {
	if in == nil {
		return nil
	}
	out := new(AppBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppBackupStatus) DeepCopyInto(out *AppBackupStatus) {
	*out = *in
	in.ScheduleStatus.DeepCopyInto(&out.ScheduleStatus)
	in.BackupStatus.DeepCopyInto(&out.BackupStatus)
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]BackupRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAction != nil {
		in, out := &in.LastAction, &out.LastAction
		*out = new(BackupAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppBackupStatus.
func (in *AppBackupStatus) DeepCopy() *AppBackupStatus {
	if in == nil {
		return nil
	}
	out := new(AppBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRestore) DeepCopyInto(out *AppRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRestore.
func (in *AppRestore) DeepCopy() *AppRestore {
	if in == nil {
		return nil
	}
	out := new(AppRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRestoreList) DeepCopyInto(out *AppRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRestoreList.
func (in *AppRestoreList) DeepCopy() *AppRestoreList {
	if in == nil {
		return nil
	}
	out := new(AppRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRestoreSpec) DeepCopyInto(out *AppRestoreSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(RestoreAction)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceModifierRules != nil {
		in, out := &in.ResourceModifierRules, &out.ResourceModifierRules
		*out = make([]ResourceModifierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRestoreSpec.
func (in *AppRestoreSpec) DeepCopy() *AppRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(AppRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRestoreStatus) DeepCopyInto(out *AppRestoreStatus) {
	*out = *in
	in.RestoreStatus.DeepCopyInto(&out.RestoreStatus)
	if in.LastAction != nil {
		in, out := &in.LastAction, &out.LastAction
		*out = new(RestoreAction)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRestoreStatus.
func (in *AppRestoreStatus) DeepCopy() *AppRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(AppRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssociatedResource) DeepCopyInto(out *AssociatedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssociatedResource.
func (in *AssociatedResource) DeepCopy() *AssociatedResource {
	if in == nil {
		return nil
	}
	out := new(AssociatedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupAction) DeepCopyInto(out *BackupAction) {
	*out = *in
	in.RequestAt.DeepCopyInto(&out.RequestAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupAction.
func (in *BackupAction) DeepCopy() *BackupAction {
	if in == nil {
		return nil
	}
	out := new(BackupAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicy) DeepCopyInto(out *BackupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicy.
func (in *BackupPolicy) DeepCopy() *BackupPolicy {
	if in == nil {
		return nil
	}
	out := new(BackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicyList) DeepCopyInto(out *BackupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicyList.
func (in *BackupPolicyList) DeepCopy() *BackupPolicyList {
	if in == nil {
		return nil
	}
	out := new(BackupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicySpec) DeepCopyInto(out *BackupPolicySpec) {
	*out = *in
	out.TTL = in.TTL
	in.StartTime.DeepCopyInto(&out.StartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicySpec.
func (in *BackupPolicySpec) DeepCopy() *BackupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(BackupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupPolicyStatus) DeepCopyInto(out *BackupPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupPolicyStatus.
func (in *BackupPolicyStatus) DeepCopy() *BackupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BackupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRecord) DeepCopyInto(out *BackupRecord) {
	*out = *in
	if in.StartTimestamp != nil {
		in, out := &in.StartTimestamp, &out.StartTimestamp
		*out = (*in).DeepCopy()
	}
	if in.CompletionTimestamp != nil {
		in, out := &in.CompletionTimestamp, &out.CompletionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = (*in).DeepCopy()
	}
	if in.VeleroStatus != nil {
		in, out := &in.VeleroStatus, &out.VeleroStatus
		*out = new(velerov1.BackupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRecord.
func (in *BackupRecord) DeepCopy() *BackupRecord {
	if in == nil {
		return nil
	}
	out := new(BackupRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRestoreStatistics) DeepCopyInto(out *BackupRestoreStatistics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRestoreStatistics.
func (in *BackupRestoreStatistics) DeepCopy() *BackupRestoreStatistics {
	if in == nil {
		return nil
	}
	out := new(BackupRestoreStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRestoreStatistics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRestoreStatisticsList) DeepCopyInto(out *BackupRestoreStatisticsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupRestoreStatistics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRestoreStatisticsList.
func (in *BackupRestoreStatisticsList) DeepCopy() *BackupRestoreStatisticsList {
	if in == nil {
		return nil
	}
	out := new(BackupRestoreStatisticsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRestoreStatisticsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRestoreStatisticsSpec) DeepCopyInto(out *BackupRestoreStatisticsSpec) {
	*out = *in
	out.ScopeRef = in.ScopeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRestoreStatisticsSpec.
func (in *BackupRestoreStatisticsSpec) DeepCopy() *BackupRestoreStatisticsSpec {
	if in == nil {
		return nil
	}
	out := new(BackupRestoreStatisticsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRestoreStatisticsStatus) DeepCopyInto(out *BackupRestoreStatisticsStatus) {
	*out = *in
	out.Statistics = in.Statistics
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.AssociatedResources != nil {
		in, out := &in.AssociatedResources, &out.AssociatedResources
		*out = make([]AssociatedResource, len(*in))
		copy(*out, *in)
	}
	if in.EventLog != nil {
		in, out := &in.EventLog, &out.EventLog
		*out = make([]StatisticsEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRestoreStatisticsStatus.
func (in *BackupRestoreStatisticsStatus) DeepCopy() *BackupRestoreStatisticsStatus {
	if in == nil {
		return nil
	}
	out := new(BackupRestoreStatisticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRuntimeConfigSpec) DeepCopyInto(out *BackupRuntimeConfigSpec) {
	*out = *in
	if in.InProgressMaxWait != nil {
		in, out := &in.InProgressMaxWait, &out.InProgressMaxWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.UnknownMaxWait != nil {
		in, out := &in.UnknownMaxWait, &out.UnknownMaxWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRuntimeConfigSpec.
func (in *BackupRuntimeConfigSpec) DeepCopy() *BackupRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BackupRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BulkModifierAction) DeepCopyInto(out *BulkModifierAction) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ApplyTo != nil {
		in, out := &in.ApplyTo, &out.ApplyTo
		*out = make([]RestoreModifierApplyTarget, len(*in))
		copy(*out, *in)
	}
	if in.ImageRewrite != nil {
		in, out := &in.ImageRewrite, &out.ImageRewrite
		*out = new(DynamicImageRewriteConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BulkModifierAction.
func (in *BulkModifierAction) DeepCopy() *BulkModifierAction {
	if in == nil {
		return nil
	}
	out := new(BulkModifierAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRuntimeConfigSpec) DeepCopyInto(out *ClusterRuntimeConfigSpec) {
	*out = *in
	if in.ReconcileInterval != nil {
		in, out := &in.ReconcileInterval, &out.ReconcileInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DeletionRetryInterval != nil {
		in, out := &in.DeletionRetryInterval, &out.DeletionRetryInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.VeleroInstallTimeout != nil {
		in, out := &in.VeleroInstallTimeout, &out.VeleroInstallTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.VeleroZombieLockThreshold != nil {
		in, out := &in.VeleroZombieLockThreshold, &out.VeleroZombieLockThreshold
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRuntimeConfigSpec.
func (in *ClusterRuntimeConfigSpec) DeepCopy() *ClusterRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.KubeConfig != nil {
		in, out := &in.KubeConfig, &out.KubeConfig
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ImageSources != nil {
		in, out := &in.ImageSources, &out.ImageSources
		*out = make([]ImageSource, len(*in))
		copy(*out, *in)
	}
	if in.VeleroInstall != nil {
		in, out := &in.VeleroInstall, &out.VeleroInstall
		*out = new(VeleroInstallSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.NamespaceStats != nil {
		in, out := &in.NamespaceStats, &out.NamespaceStats
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.WorkloadNamespaceStats != nil {
		in, out := &in.WorkloadNamespaceStats, &out.WorkloadNamespaceStats
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.TokenExpiration != nil {
		in, out := &in.TokenExpiration, &out.TokenExpiration
		*out = (*in).DeepCopy()
	}
	if in.ReadyTimestamp != nil {
		in, out := &in.ReadyTimestamp, &out.ReadyTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conditions) DeepCopyInto(out *Conditions) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in *Conditions) DeepCopy() *Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSync) DeepCopyInto(out *DataSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSync.
func (in *DataSync) DeepCopy() *DataSync {
	if in == nil {
		return nil
	}
	out := new(DataSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSyncList) DeepCopyInto(out *DataSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSyncList.
func (in *DataSyncList) DeepCopy() *DataSyncList {
	if in == nil {
		return nil
	}
	out := new(DataSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSyncSpec) DeepCopyInto(out *DataSyncSpec) {
	*out = *in
	out.Trigger = in.Trigger
	if in.TrafficlessConfig != nil {
		in, out := &in.TrafficlessConfig, &out.TrafficlessConfig
		*out = new(TrafficlessConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSyncSpec.
func (in *DataSyncSpec) DeepCopy() *DataSyncSpec {
	if in == nil {
		return nil
	}
	out := new(DataSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSyncStatus) DeepCopyInto(out *DataSyncStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.TrafficlessPods != nil {
		in, out := &in.TrafficlessPods, &out.TrafficlessPods
		*out = make([]TrafficlessPodStatus, len(*in))
		copy(*out, *in)
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]SyncHistoryRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSyncStatus.
func (in *DataSyncStatus) DeepCopy() *DataSyncStatus {
	if in == nil {
		return nil
	}
	out := new(DataSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterBackup) DeepCopyInto(out *DisasterBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterBackup.
func (in *DisasterBackup) DeepCopy() *DisasterBackup {
	if in == nil {
		return nil
	}
	out := new(DisasterBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterBackupList) DeepCopyInto(out *DisasterBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterBackupList.
func (in *DisasterBackupList) DeepCopy() *DisasterBackupList {
	if in == nil {
		return nil
	}
	out := new(DisasterBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterBackupSpec) DeepCopyInto(out *DisasterBackupSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterBackupSpec.
func (in *DisasterBackupSpec) DeepCopy() *DisasterBackupSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterBackupStatus) DeepCopyInto(out *DisasterBackupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string][]Resources, len(*in))
		for key, val := range *in {
			var outVal []Resources
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]Resources, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = make(map[string][]Resources, len(*in))
		for key, val := range *in {
			var outVal []Resources
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]Resources, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	in.UpdateTime.DeepCopyInto(&out.UpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterBackupStatus.
func (in *DisasterBackupStatus) DeepCopy() *DisasterBackupStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterConfig) DeepCopyInto(out *DisasterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterConfig.
func (in *DisasterConfig) DeepCopy() *DisasterConfig {
	if in == nil {
		return nil
	}
	out := new(DisasterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterConfigList) DeepCopyInto(out *DisasterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterConfigList.
func (in *DisasterConfigList) DeepCopy() *DisasterConfigList {
	if in == nil {
		return nil
	}
	out := new(DisasterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterConfigSpec) DeepCopyInto(out *DisasterConfigSpec) {
	*out = *in
	if in.ImageRewrite != nil {
		in, out := &in.ImageRewrite, &out.ImageRewrite
		*out = new(ImageRewriteConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterConfigSpec.
func (in *DisasterConfigSpec) DeepCopy() *DisasterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterConfigStatus) DeepCopyInto(out *DisasterConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterConfigStatus.
func (in *DisasterConfigStatus) DeepCopy() *DisasterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterDrill) DeepCopyInto(out *DisasterDrill) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterDrill.
func (in *DisasterDrill) DeepCopy() *DisasterDrill {
	if in == nil {
		return nil
	}
	out := new(DisasterDrill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterDrill) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterDrillList) DeepCopyInto(out *DisasterDrillList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterDrill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterDrillList.
func (in *DisasterDrillList) DeepCopy() *DisasterDrillList {
	if in == nil {
		return nil
	}
	out := new(DisasterDrillList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterDrillList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterDrillSpec) DeepCopyInto(out *DisasterDrillSpec) {
	*out = *in
	if in.NamespaceMapping != nil {
		in, out := &in.NamespaceMapping, &out.NamespaceMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RestorePolicy != nil {
		in, out := &in.RestorePolicy, &out.RestorePolicy
		*out = new(RestorePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.VeleroHooks != nil {
		in, out := &in.VeleroHooks, &out.VeleroHooks
		*out = new(DisasterVeleroHooks)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterDrillSpec.
func (in *DisasterDrillSpec) DeepCopy() *DisasterDrillSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterDrillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterDrillStatus) DeepCopyInto(out *DisasterDrillStatus) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyTime != nil {
		in, out := &in.ReadyTime, &out.ReadyTime
		*out = (*in).DeepCopy()
	}
	if in.ExecutionTime != nil {
		in, out := &in.ExecutionTime, &out.ExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ValidationResults != nil {
		in, out := &in.ValidationResults, &out.ValidationResults
		*out = new(DrillValidationResults)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupProgress != nil {
		in, out := &in.GroupProgress, &out.GroupProgress
		*out = new(GroupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterDrillStatus.
func (in *DisasterDrillStatus) DeepCopy() *DisasterDrillStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterDrillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterGroup) DeepCopyInto(out *DisasterGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterGroup.
func (in *DisasterGroup) DeepCopy() *DisasterGroup {
	if in == nil {
		return nil
	}
	out := new(DisasterGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterGroupList) DeepCopyInto(out *DisasterGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterGroupList.
func (in *DisasterGroupList) DeepCopy() *DisasterGroupList {
	if in == nil {
		return nil
	}
	out := new(DisasterGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterGroupPolicy) DeepCopyInto(out *DisasterGroupPolicy) {
	*out = *in
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterGroupPolicy.
func (in *DisasterGroupPolicy) DeepCopy() *DisasterGroupPolicy {
	if in == nil {
		return nil
	}
	out := new(DisasterGroupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterGroupSpec) DeepCopyInto(out *DisasterGroupSpec) {
	*out = *in
	if in.Levels != nil {
		in, out := &in.Levels, &out.Levels
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	in.Policy.DeepCopyInto(&out.Policy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterGroupSpec.
func (in *DisasterGroupSpec) DeepCopy() *DisasterGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterGroupStatus) DeepCopyInto(out *DisasterGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterGroupStatus.
func (in *DisasterGroupStatus) DeepCopy() *DisasterGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterInstance) DeepCopyInto(out *DisasterInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterInstance.
func (in *DisasterInstance) DeepCopy() *DisasterInstance {
	if in == nil {
		return nil
	}
	out := new(DisasterInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterInstanceList) DeepCopyInto(out *DisasterInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterInstanceList.
func (in *DisasterInstanceList) DeepCopy() *DisasterInstanceList {
	if in == nil {
		return nil
	}
	out := new(DisasterInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterInstanceSpec) DeepCopyInto(out *DisasterInstanceSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RestorePolicy != nil {
		in, out := &in.RestorePolicy, &out.RestorePolicy
		*out = new(RestorePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.VeleroHooks != nil {
		in, out := &in.VeleroHooks, &out.VeleroHooks
		*out = new(DisasterVeleroHooks)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipPodReadyCheck != nil {
		in, out := &in.SkipPodReadyCheck, &out.SkipPodReadyCheck
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterInstanceSpec.
func (in *DisasterInstanceSpec) DeepCopy() *DisasterInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterInstanceStatus) DeepCopyInto(out *DisasterInstanceStatus) {
	*out = *in
	if in.LastDataSyncTime != nil {
		in, out := &in.LastDataSyncTime, &out.LastDataSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastResourceSyncTime != nil {
		in, out := &in.LastResourceSyncTime, &out.LastResourceSyncTime
		*out = (*in).DeepCopy()
	}
	if in.AvailableOperations != nil {
		in, out := &in.AvailableOperations, &out.AvailableOperations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterInstanceStatus.
func (in *DisasterInstanceStatus) DeepCopy() *DisasterInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterJob) DeepCopyInto(out *DisasterJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterJob.
func (in *DisasterJob) DeepCopy() *DisasterJob {
	if in == nil {
		return nil
	}
	out := new(DisasterJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterJobList) DeepCopyInto(out *DisasterJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterJobList.
func (in *DisasterJobList) DeepCopy() *DisasterJobList {
	if in == nil {
		return nil
	}
	out := new(DisasterJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterJobSpec) DeepCopyInto(out *DisasterJobSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterJobSpec.
func (in *DisasterJobSpec) DeepCopy() *DisasterJobSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterJobStatus) DeepCopyInto(out *DisasterJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StartTime.DeepCopyInto(&out.StartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterJobStatus.
func (in *DisasterJobStatus) DeepCopy() *DisasterJobStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterOperation) DeepCopyInto(out *DisasterOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterOperation.
func (in *DisasterOperation) DeepCopy() *DisasterOperation {
	if in == nil {
		return nil
	}
	out := new(DisasterOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterOperationList) DeepCopyInto(out *DisasterOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterOperationList.
func (in *DisasterOperationList) DeepCopy() *DisasterOperationList {
	if in == nil {
		return nil
	}
	out := new(DisasterOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterOperationSpec) DeepCopyInto(out *DisasterOperationSpec) {
	*out = *in
	if in.DrillConfig != nil {
		in, out := &in.DrillConfig, &out.DrillConfig
		*out = new(DrillConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Directive != nil {
		in, out := &in.Directive, &out.Directive
		*out = new(OperationDirective)
		**out = **in
	}
	if in.SkipPodReadyCheck != nil {
		in, out := &in.SkipPodReadyCheck, &out.SkipPodReadyCheck
		*out = new(bool)
		**out = **in
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterOperationSpec.
func (in *DisasterOperationSpec) DeepCopy() *DisasterOperationSpec {
	if in == nil {
		return nil
	}
	out := new(DisasterOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterOperationStatus) DeepCopyInto(out *DisasterOperationStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoCancelSteps != nil {
		in, out := &in.AutoCancelSteps, &out.AutoCancelSteps
		*out = make([]StepStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoCancelTriggeredAt != nil {
		in, out := &in.AutoCancelTriggeredAt, &out.AutoCancelTriggeredAt
		*out = (*in).DeepCopy()
	}
	if in.AutoCancelCompletionTime != nil {
		in, out := &in.AutoCancelCompletionTime, &out.AutoCancelCompletionTime
		*out = (*in).DeepCopy()
	}
	if in.RoleStatus != nil {
		in, out := &in.RoleStatus, &out.RoleStatus
		*out = new(RoleStatus)
		**out = **in
	}
	if in.GroupStatus != nil {
		in, out := &in.GroupStatus, &out.GroupStatus
		*out = new(GroupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NextRetryTime != nil {
		in, out := &in.NextRetryTime, &out.NextRetryTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterOperationStatus.
func (in *DisasterOperationStatus) DeepCopy() *DisasterOperationStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterPolicy) DeepCopyInto(out *DisasterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterPolicy.
func (in *DisasterPolicy) DeepCopy() *DisasterPolicy {
	if in == nil {
		return nil
	}
	out := new(DisasterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterPolicyList) DeepCopyInto(out *DisasterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DisasterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterPolicyList.
func (in *DisasterPolicyList) DeepCopy() *DisasterPolicyList {
	if in == nil {
		return nil
	}
	out := new(DisasterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DisasterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterPolicySpec) DeepCopyInto(out *DisasterPolicySpec) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterPolicySpec.
func (in *DisasterPolicySpec) DeepCopy() *DisasterPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DisasterPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterPolicyStatus) DeepCopyInto(out *DisasterPolicyStatus) {
	*out = *in
	if in.LastExecutionTime != nil {
		in, out := &in.LastExecutionTime, &out.LastExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.NextExecutionTime != nil {
		in, out := &in.NextExecutionTime, &out.NextExecutionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterPolicyStatus.
func (in *DisasterPolicyStatus) DeepCopy() *DisasterPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterVeleroHooks) DeepCopyInto(out *DisasterVeleroHooks) {
	*out = *in
	if in.DataBackup != nil {
		in, out := &in.DataBackup, &out.DataBackup
		*out = new(velerov1.BackupHooks)
		(*in).DeepCopyInto(*out)
	}
	if in.DataRestore != nil {
		in, out := &in.DataRestore, &out.DataRestore
		*out = new(velerov1.RestoreHooks)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterVeleroHooks.
func (in *DisasterVeleroHooks) DeepCopy() *DisasterVeleroHooks {
	if in == nil {
		return nil
	}
	out := new(DisasterVeleroHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrillConfig) DeepCopyInto(out *DrillConfig) {
	*out = *in
	if in.NamespaceMapping != nil {
		in, out := &in.NamespaceMapping, &out.NamespaceMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RestorePolicy != nil {
		in, out := &in.RestorePolicy, &out.RestorePolicy
		*out = new(RestorePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.VeleroHooks != nil {
		in, out := &in.VeleroHooks, &out.VeleroHooks
		*out = new(DisasterVeleroHooks)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrillConfig.
func (in *DrillConfig) DeepCopy() *DrillConfig {
	if in == nil {
		return nil
	}
	out := new(DrillConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrillValidationResults) DeepCopyInto(out *DrillValidationResults) {
	*out = *in
	if in.LastDataSyncTime != nil {
		in, out := &in.LastDataSyncTime, &out.LastDataSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastResourceSyncTime != nil {
		in, out := &in.LastResourceSyncTime, &out.LastResourceSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrillValidationResults.
func (in *DrillValidationResults) DeepCopy() *DrillValidationResults {
	if in == nil {
		return nil
	}
	out := new(DrillValidationResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicImageRewriteConfig) DeepCopyInto(out *DynamicImageRewriteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicImageRewriteConfig.
func (in *DynamicImageRewriteConfig) DeepCopy() *DynamicImageRewriteConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicImageRewriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
	if in.LevelStatuses != nil {
		in, out := &in.LevelStatuses, &out.LevelStatuses
		*out = make([]LevelStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRewriteConfig) DeepCopyInto(out *ImageRewriteConfig) {
	*out = *in
	if in.ApplyTo != nil {
		in, out := &in.ApplyTo, &out.ApplyTo
		*out = make([]ImageRewriteApplyTarget, len(*in))
		copy(*out, *in)
	}
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]ImageSourceMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRewriteConfig.
func (in *ImageRewriteConfig) DeepCopy() *ImageRewriteConfig {
	if in == nil {
		return nil
	}
	out := new(ImageRewriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSource) DeepCopyInto(out *ImageSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSource.
func (in *ImageSource) DeepCopy() *ImageSource {
	if in == nil {
		return nil
	}
	out := new(ImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSourceMapping) DeepCopyInto(out *ImageSourceMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSourceMapping.
func (in *ImageSourceMapping) DeepCopy() *ImageSourceMapping {
	if in == nil {
		return nil
	}
	out := new(ImageSourceMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRuntimeConfigSpec) DeepCopyInto(out *InstanceRuntimeConfigSpec) {
	*out = *in
	if in.TransitionWatchdogTimeout != nil {
		in, out := &in.TransitionWatchdogTimeout, &out.TransitionWatchdogTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MinTransitionWatchdogTimeout != nil {
		in, out := &in.MinTransitionWatchdogTimeout, &out.MinTransitionWatchdogTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.InitializingRequeue != nil {
		in, out := &in.InitializingRequeue, &out.InitializingRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.SteadyRequeue != nil {
		in, out := &in.SteadyRequeue, &out.SteadyRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FailedRequeue != nil {
		in, out := &in.FailedRequeue, &out.FailedRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRuntimeConfigSpec.
func (in *InstanceRuntimeConfigSpec) DeepCopy() *InstanceRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JSONPatch) DeepCopyInto(out *JSONPatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONPatch.
func (in *JSONPatch) DeepCopy() *JSONPatch {
	if in == nil {
		return nil
	}
	out := new(JSONPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LevelStatus) DeepCopyInto(out *LevelStatus) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.FailedInstances != nil {
		in, out := &in.FailedInstances, &out.FailedInstances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LevelStatus.
func (in *LevelStatus) DeepCopy() *LevelStatus {
	if in == nil {
		return nil
	}
	out := new(LevelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationDirective) DeepCopyInto(out *OperationDirective) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationDirective.
func (in *OperationDirective) DeepCopy() *OperationDirective {
	if in == nil {
		return nil
	}
	out := new(OperationDirective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRuntimeConfigSpec) DeepCopyInto(out *OperationRuntimeConfigSpec) {
	*out = *in
	if in.DefaultTimeoutMinutes != nil {
		in, out := &in.DefaultTimeoutMinutes, &out.DefaultTimeoutMinutes
		*out = new(int32)
		**out = **in
	}
	if in.StepStartRequeue != nil {
		in, out := &in.StepStartRequeue, &out.StepStartRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.StepRunningRequeue != nil {
		in, out := &in.StepRunningRequeue, &out.StepRunningRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.DefaultRetryInterval != nil {
		in, out := &in.DefaultRetryInterval, &out.DefaultRetryInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRuntimeConfigSpec.
func (in *OperationRuntimeConfigSpec) DeepCopy() *OperationRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OperationRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorRuntimeConfig) DeepCopyInto(out *OperatorRuntimeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorRuntimeConfig.
func (in *OperatorRuntimeConfig) DeepCopy() *OperatorRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorRuntimeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorRuntimeConfigList) DeepCopyInto(out *OperatorRuntimeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatorRuntimeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorRuntimeConfigList.
func (in *OperatorRuntimeConfigList) DeepCopy() *OperatorRuntimeConfigList {
	if in == nil {
		return nil
	}
	out := new(OperatorRuntimeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorRuntimeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorRuntimeConfigSpec) DeepCopyInto(out *OperatorRuntimeConfigSpec) {
	*out = *in
	if in.BackupRuntime != nil {
		in, out := &in.BackupRuntime, &out.BackupRuntime
		*out = new(BackupRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RestoreRuntime != nil {
		in, out := &in.RestoreRuntime, &out.RestoreRuntime
		*out = new(RestoreRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OperationRuntime != nil {
		in, out := &in.OperationRuntime, &out.OperationRuntime
		*out = new(OperationRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceRuntime != nil {
		in, out := &in.InstanceRuntime, &out.InstanceRuntime
		*out = new(InstanceRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SyncRuntime != nil {
		in, out := &in.SyncRuntime, &out.SyncRuntime
		*out = new(SyncRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageRuntime != nil {
		in, out := &in.StorageRuntime, &out.StorageRuntime
		*out = new(StorageRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterRuntime != nil {
		in, out := &in.ClusterRuntime, &out.ClusterRuntime
		*out = new(ClusterRuntimeConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorRuntimeConfigSpec.
func (in *OperatorRuntimeConfigSpec) DeepCopy() *OperatorRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorRuntimeConfigStatus) DeepCopyInto(out *OperatorRuntimeConfigStatus) {
	*out = *in
	if in.LastActivatedTime != nil {
		in, out := &in.LastActivatedTime, &out.LastActivatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorRuntimeConfigStatus.
func (in *OperatorRuntimeConfigStatus) DeepCopy() *OperatorRuntimeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorRuntimeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceModifierRule) DeepCopyInto(out *ResourceModifierRule) {
	*out = *in
	in.Conditions.DeepCopyInto(&out.Conditions)
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]JSONPatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceModifierRule.
func (in *ResourceModifierRule) DeepCopy() *ResourceModifierRule {
	if in == nil {
		return nil
	}
	out := new(ResourceModifierRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSync) DeepCopyInto(out *ResourceSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSync.
func (in *ResourceSync) DeepCopy() *ResourceSync {
	if in == nil {
		return nil
	}
	out := new(ResourceSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncList) DeepCopyInto(out *ResourceSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncList.
func (in *ResourceSyncList) DeepCopy() *ResourceSyncList {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncSpec) DeepCopyInto(out *ResourceSyncSpec) {
	*out = *in
	out.Trigger = in.Trigger
	if in.StandbyModifier != nil {
		in, out := &in.StandbyModifier, &out.StandbyModifier
		*out = new(StandbyModifierConfig)
		**out = **in
	}
	if in.ExcludeResources != nil {
		in, out := &in.ExcludeResources, &out.ExcludeResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncSpec.
func (in *ResourceSyncSpec) DeepCopy() *ResourceSyncSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSyncStatus) DeepCopyInto(out *ResourceSyncStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]SyncHistoryRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSyncStatus.
func (in *ResourceSyncStatus) DeepCopy() *ResourceSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreAction) DeepCopyInto(out *RestoreAction) {
	*out = *in
	in.RequestAt.DeepCopyInto(&out.RequestAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreAction.
func (in *RestoreAction) DeepCopy() *RestoreAction {
	if in == nil {
		return nil
	}
	out := new(RestoreAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreClassMapping) DeepCopyInto(out *RestoreClassMapping) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreClassMapping.
func (in *RestoreClassMapping) DeepCopy() *RestoreClassMapping {
	if in == nil {
		return nil
	}
	out := new(RestoreClassMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreClassMappingPolicy) DeepCopyInto(out *RestoreClassMappingPolicy) {
	*out = *in
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]RestoreClassMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreClassMappingPolicy.
func (in *RestoreClassMappingPolicy) DeepCopy() *RestoreClassMappingPolicy {
	if in == nil {
		return nil
	}
	out := new(RestoreClassMappingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreExecutionPolicy) DeepCopyInto(out *RestoreExecutionPolicy) {
	*out = *in
	if in.RestorePVs != nil {
		in, out := &in.RestorePVs, &out.RestorePVs
		*out = new(bool)
		**out = **in
	}
	if in.ItemOperationTimeout != nil {
		in, out := &in.ItemOperationTimeout, &out.ItemOperationTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreExecutionPolicy.
func (in *RestoreExecutionPolicy) DeepCopy() *RestoreExecutionPolicy {
	if in == nil {
		return nil
	}
	out := new(RestoreExecutionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreModifierPair) DeepCopyInto(out *RestoreModifierPair) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreModifierPair.
func (in *RestoreModifierPair) DeepCopy() *RestoreModifierPair {
	if in == nil {
		return nil
	}
	out := new(RestoreModifierPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreModifierRule) DeepCopyInto(out *RestoreModifierRule) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ApplyTo != nil {
		in, out := &in.ApplyTo, &out.ApplyTo
		*out = make([]RestoreModifierApplyTarget, len(*in))
		copy(*out, *in)
	}
	in.Conditions.DeepCopyInto(&out.Conditions)
	if in.VeleroRule != nil {
		in, out := &in.VeleroRule, &out.VeleroRule
		*out = new(RestoreModifierVeleroRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Pair != nil {
		in, out := &in.Pair, &out.Pair
		*out = new(RestoreModifierPair)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreModifierRule.
func (in *RestoreModifierRule) DeepCopy() *RestoreModifierRule {
	if in == nil {
		return nil
	}
	out := new(RestoreModifierRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreModifierVeleroRule) DeepCopyInto(out *RestoreModifierVeleroRule) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]JSONPatch, len(*in))
		copy(*out, *in)
	}
	if in.MergePatches != nil {
		in, out := &in.MergePatches, &out.MergePatches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StrategicPatches != nil {
		in, out := &in.StrategicPatches, &out.StrategicPatches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreModifierVeleroRule.
func (in *RestoreModifierVeleroRule) DeepCopy() *RestoreModifierVeleroRule {
	if in == nil {
		return nil
	}
	out := new(RestoreModifierVeleroRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicy) DeepCopyInto(out *RestorePolicy) {
	*out = *in
	if in.ResourceSelection != nil {
		in, out := &in.ResourceSelection, &out.ResourceSelection
		*out = new(RestoreResourceSelectionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(RestoreExecutionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClassMapping != nil {
		in, out := &in.StorageClassMapping, &out.StorageClassMapping
		*out = new(RestoreClassMappingPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressClassMapping != nil {
		in, out := &in.IngressClassMapping, &out.IngressClassMapping
		*out = new(RestoreClassMappingPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.BulkModifierActions != nil {
		in, out := &in.BulkModifierActions, &out.BulkModifierActions
		*out = make([]BulkModifierAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModifierRules != nil {
		in, out := &in.ModifierRules, &out.ModifierRules
		*out = make([]RestoreModifierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModifierRuleSnapshot != nil {
		in, out := &in.ModifierRuleSnapshot, &out.ModifierRuleSnapshot
		*out = make([]RestoreModifierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UseUnifiedDirectionResolver != nil {
		in, out := &in.UseUnifiedDirectionResolver, &out.UseUnifiedDirectionResolver
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicy.
func (in *RestorePolicy) DeepCopy() *RestorePolicy {
	if in == nil {
		return nil
	}
	out := new(RestorePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreResourceSelectionPolicy) DeepCopyInto(out *RestoreResourceSelectionPolicy) {
	*out = *in
	if in.IncludedNamespaces != nil {
		in, out := &in.IncludedNamespaces, &out.IncludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludedResources != nil {
		in, out := &in.IncludedResources, &out.IncludedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedResources != nil {
		in, out := &in.ExcludedResources, &out.ExcludedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludedNamespaceScopedResources != nil {
		in, out := &in.IncludedNamespaceScopedResources, &out.IncludedNamespaceScopedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedNamespaceScopedResources != nil {
		in, out := &in.ExcludedNamespaceScopedResources, &out.ExcludedNamespaceScopedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludedClusterScopedResources != nil {
		in, out := &in.IncludedClusterScopedResources, &out.IncludedClusterScopedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedClusterScopedResources != nil {
		in, out := &in.ExcludedClusterScopedResources, &out.ExcludedClusterScopedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IncludeClusterResources != nil {
		in, out := &in.IncludeClusterResources, &out.IncludeClusterResources
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreResourceSelectionPolicy.
func (in *RestoreResourceSelectionPolicy) DeepCopy() *RestoreResourceSelectionPolicy {
	if in == nil {
		return nil
	}
	out := new(RestoreResourceSelectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreRuntimeConfigSpec) DeepCopyInto(out *RestoreRuntimeConfigSpec) {
	*out = *in
	if in.InProgressMaxWait != nil {
		in, out := &in.InProgressMaxWait, &out.InProgressMaxWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.UnknownMaxWait != nil {
		in, out := &in.UnknownMaxWait, &out.UnknownMaxWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.InProgressPollInterval != nil {
		in, out := &in.InProgressPollInterval, &out.InProgressPollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.UnknownPollInterval != nil {
		in, out := &in.UnknownPollInterval, &out.UnknownPollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ProgressCompleteGrace != nil {
		in, out := &in.ProgressCompleteGrace, &out.ProgressCompleteGrace
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.StartupGrace != nil {
		in, out := &in.StartupGrace, &out.StartupGrace
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MissingGrace != nil {
		in, out := &in.MissingGrace, &out.MissingGrace
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.EmptyStatusGrace != nil {
		in, out := &in.EmptyStatusGrace, &out.EmptyStatusGrace
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.PodVolumeRestorePendingWait != nil {
		in, out := &in.PodVolumeRestorePendingWait, &out.PodVolumeRestorePendingWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RetryBackoff != nil {
		in, out := &in.RetryBackoff, &out.RetryBackoff
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RetryLimit != nil {
		in, out := &in.RetryLimit, &out.RetryLimit
		*out = new(int32)
		**out = **in
	}
	if in.RetryLimitProgress != nil {
		in, out := &in.RetryLimitProgress, &out.RetryLimitProgress
		*out = new(int32)
		**out = **in
	}
	if in.RetryLimitStartup != nil {
		in, out := &in.RetryLimitStartup, &out.RetryLimitStartup
		*out = new(int32)
		**out = **in
	}
	if in.RetryLimitMissing != nil {
		in, out := &in.RetryLimitMissing, &out.RetryLimitMissing
		*out = new(int32)
		**out = **in
	}
	if in.RetryLimitEmpty != nil {
		in, out := &in.RetryLimitEmpty, &out.RetryLimitEmpty
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreRuntimeConfigSpec.
func (in *RestoreRuntimeConfigSpec) DeepCopy() *RestoreRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStatus) DeepCopyInto(out *RoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatus.
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeReference) DeepCopyInto(out *ScopeReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeReference.
func (in *ScopeReference) DeepCopy() *ScopeReference {
	if in == nil {
		return nil
	}
	out := new(ScopeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandbyModifierConfig) DeepCopyInto(out *StandbyModifierConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandbyModifierConfig.
func (in *StandbyModifierConfig) DeepCopy() *StandbyModifierConfig {
	if in == nil {
		return nil
	}
	out := new(StandbyModifierConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatisticsData) DeepCopyInto(out *StatisticsData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatisticsData.
func (in *StatisticsData) DeepCopy() *StatisticsData {
	if in == nil {
		return nil
	}
	out := new(StatisticsData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatisticsEvent) DeepCopyInto(out *StatisticsEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatisticsEvent.
func (in *StatisticsEvent) DeepCopy() *StatisticsEvent {
	if in == nil {
		return nil
	}
	out := new(StatisticsEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepStatus) DeepCopyInto(out *StepStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepStatus.
func (in *StepStatus) DeepCopy() *StepStatus {
	if in == nil {
		return nil
	}
	out := new(StepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRepository) DeepCopyInto(out *StorageRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRepository.
func (in *StorageRepository) DeepCopy() *StorageRepository {
	if in == nil {
		return nil
	}
	out := new(StorageRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRepositoryList) DeepCopyInto(out *StorageRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRepositoryList.
func (in *StorageRepositoryList) DeepCopy() *StorageRepositoryList {
	if in == nil {
		return nil
	}
	out := new(StorageRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRepositorySpec) DeepCopyInto(out *StorageRepositorySpec) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRepositorySpec.
func (in *StorageRepositorySpec) DeepCopy() *StorageRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(StorageRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRepositoryStatus) DeepCopyInto(out *StorageRepositoryStatus) {
	*out = *in
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyTimestamp != nil {
		in, out := &in.ReadyTimestamp, &out.ReadyTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRepositoryStatus.
func (in *StorageRepositoryStatus) DeepCopy() *StorageRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(StorageRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageRuntimeConfigSpec) DeepCopyInto(out *StorageRuntimeConfigSpec) {
	*out = *in
	if in.RequeueInterval != nil {
		in, out := &in.RequeueInterval, &out.RequeueInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageRuntimeConfigSpec.
func (in *StorageRuntimeConfigSpec) DeepCopy() *StorageRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(StorageRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncHistoryHookStatus) DeepCopyInto(out *SyncHistoryHookStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncHistoryHookStatus.
func (in *SyncHistoryHookStatus) DeepCopy() *SyncHistoryHookStatus {
	if in == nil {
		return nil
	}
	out := new(SyncHistoryHookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncHistoryRecord) DeepCopyInto(out *SyncHistoryRecord) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.BackupHookStatus != nil {
		in, out := &in.BackupHookStatus, &out.BackupHookStatus
		*out = new(SyncHistoryHookStatus)
		**out = **in
	}
	if in.RestoreHookStatus != nil {
		in, out := &in.RestoreHookStatus, &out.RestoreHookStatus
		*out = new(SyncHistoryHookStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncHistoryRecord.
func (in *SyncHistoryRecord) DeepCopy() *SyncHistoryRecord {
	if in == nil {
		return nil
	}
	out := new(SyncHistoryRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncRuntimeConfigSpec) DeepCopyInto(out *SyncRuntimeConfigSpec) {
	*out = *in
	if in.SchedulerUpdateTimeout != nil {
		in, out := &in.SchedulerUpdateTimeout, &out.SchedulerUpdateTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BackupObserveRequeue != nil {
		in, out := &in.BackupObserveRequeue, &out.BackupObserveRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BackupInProgressRequeue != nil {
		in, out := &in.BackupInProgressRequeue, &out.BackupInProgressRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HistoryMissingRequeue != nil {
		in, out := &in.HistoryMissingRequeue, &out.HistoryMissingRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.RestoreObserveRequeue != nil {
		in, out := &in.RestoreObserveRequeue, &out.RestoreObserveRequeue
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HistoryRetention != nil {
		in, out := &in.HistoryRetention, &out.HistoryRetention
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncRuntimeConfigSpec.
func (in *SyncRuntimeConfigSpec) DeepCopy() *SyncRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SyncRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficlessConfig) DeepCopyInto(out *TrafficlessConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoveLabels != nil {
		in, out := &in.RemoveLabels, &out.RemoveLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficlessConfig.
func (in *TrafficlessConfig) DeepCopy() *TrafficlessConfig {
	if in == nil {
		return nil
	}
	out := new(TrafficlessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficlessPodStatus) DeepCopyInto(out *TrafficlessPodStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficlessPodStatus.
func (in *TrafficlessPodStatus) DeepCopy() *TrafficlessPodStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficlessPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSpec) DeepCopyInto(out *TriggerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSpec.
func (in *TriggerSpec) DeepCopy() *TriggerSpec {
	if in == nil {
		return nil
	}
	out := new(TriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroInstallSpec) DeepCopyInto(out *VeleroInstallSpec) {
	*out = *in
	if in.RegistryCredentialSecretRef != nil {
		in, out := &in.RegistryCredentialSecretRef, &out.RegistryCredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroInstallSpec.
func (in *VeleroInstallSpec) DeepCopy() *VeleroInstallSpec {
	if in == nil {
		return nil
	}
	out := new(VeleroInstallSpec)
	in.DeepCopyInto(out)
	return out
}
