/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	disasterv1 "github.com/softcdata/testudo-operator/pkg/clientset/versioned/typed/disaster/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBackupPolicies implements BackupPolicyInterface
type fakeBackupPolicies struct {
	*gentype.FakeClientWithList[*v1.BackupPolicy, *v1.BackupPolicyList]
	Fake *FakeDisasterV1
}

func newFakeBackupPolicies(fake *FakeDisasterV1, namespace string) disasterv1.BackupPolicyInterface {
	return &fakeBackupPolicies{
		gentype.NewFakeClientWithList[*v1.BackupPolicy, *v1.BackupPolicyList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("backuppolicies"),
			v1.SchemeGroupVersion.WithKind("BackupPolicy"),
			func() *v1.BackupPolicy { return &v1.BackupPolicy{} },
			func() *v1.BackupPolicyList { return &v1.BackupPolicyList{} },
			func(dst, src *v1.BackupPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.BackupPolicyList) []*v1.BackupPolicy { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.BackupPolicyList, items []*v1.BackupPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
