/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/softcdata/testudo-operator/pkg/clientset/versioned/typed/disaster/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDisasterV1 struct {
	*testing.Fake
}

func (c *FakeDisasterV1) AppBackups(namespace string) v1.AppBackupInterface {
	return newFakeAppBackups(c, namespace)
}

func (c *FakeDisasterV1) AppRestores(namespace string) v1.AppRestoreInterface {
	return newFakeAppRestores(c, namespace)
}

func (c *FakeDisasterV1) BackupPolicies(namespace string) v1.BackupPolicyInterface {
	return newFakeBackupPolicies(c, namespace)
}

func (c *FakeDisasterV1) BackupRestoreStatisticses(namespace string) v1.BackupRestoreStatisticsInterface {
	return newFakeBackupRestoreStatisticses(c, namespace)
}

func (c *FakeDisasterV1) Clusters() v1.ClusterInterface {
	return newFakeClusters(c)
}

func (c *FakeDisasterV1) DataSyncs(namespace string) v1.DataSyncInterface {
	return newFakeDataSyncs(c, namespace)
}

func (c *FakeDisasterV1) DisasterBackups(namespace string) v1.DisasterBackupInterface {
	return newFakeDisasterBackups(c, namespace)
}

func (c *FakeDisasterV1) DisasterConfigs() v1.DisasterConfigInterface {
	return newFakeDisasterConfigs(c)
}

func (c *FakeDisasterV1) DisasterDrills(namespace string) v1.DisasterDrillInterface {
	return newFakeDisasterDrills(c, namespace)
}

func (c *FakeDisasterV1) DisasterGroups(namespace string) v1.DisasterGroupInterface {
	return newFakeDisasterGroups(c, namespace)
}

func (c *FakeDisasterV1) DisasterInstances(namespace string) v1.DisasterInstanceInterface {
	return newFakeDisasterInstances(c, namespace)
}

func (c *FakeDisasterV1) DisasterJobs(namespace string) v1.DisasterJobInterface {
	return newFakeDisasterJobs(c, namespace)
}

func (c *FakeDisasterV1) DisasterOperations(namespace string) v1.DisasterOperationInterface {
	return newFakeDisasterOperations(c, namespace)
}

func (c *FakeDisasterV1) DisasterPolicies(namespace string) v1.DisasterPolicyInterface {
	return newFakeDisasterPolicies(c, namespace)
}

func (c *FakeDisasterV1) ResourceSyncs(namespace string) v1.ResourceSyncInterface {
	return newFakeResourceSyncs(c, namespace)
}

func (c *FakeDisasterV1) StorageRepositories(namespace string) v1.StorageRepositoryInterface {
	return newFakeStorageRepositories(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDisasterV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
