/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	scheme "github.com/softcdata/testudo-operator/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DisasterInstancesGetter has a method to return a DisasterInstanceInterface.
// A group's client should implement this interface.
type DisasterInstancesGetter interface {
	DisasterInstances(namespace string) DisasterInstanceInterface
}

// DisasterInstanceInterface has methods to work with DisasterInstance resources.
type DisasterInstanceInterface interface {
	Create(ctx context.Context, disasterInstance *disasterv1.DisasterInstance, opts metav1.CreateOptions) (*disasterv1.DisasterInstance, error)
	Update(ctx context.Context, disasterInstance *disasterv1.DisasterInstance, opts metav1.UpdateOptions) (*disasterv1.DisasterInstance, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, disasterInstance *disasterv1.DisasterInstance, opts metav1.UpdateOptions) (*disasterv1.DisasterInstance, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*disasterv1.DisasterInstance, error)
	List(ctx context.Context, opts metav1.ListOptions) (*disasterv1.DisasterInstanceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *disasterv1.DisasterInstance, err error)
	DisasterInstanceExpansion
}

// disasterInstances implements DisasterInstanceInterface
type disasterInstances struct {
	*gentype.ClientWithList[*disasterv1.DisasterInstance, *disasterv1.DisasterInstanceList]
}

// newDisasterInstances returns a DisasterInstances
func newDisasterInstances(c *DisasterV1Client, namespace string) *disasterInstances {
	return &disasterInstances{
		gentype.NewClientWithList[*disasterv1.DisasterInstance, *disasterv1.DisasterInstanceList](
			"disasterinstances",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *disasterv1.DisasterInstance { return &disasterv1.DisasterInstance{} },
			func() *disasterv1.DisasterInstanceList { return &disasterv1.DisasterInstanceList{} },
		),
	}
}
