/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	scheme "github.com/softcdata/testudo-operator/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DisasterBackupsGetter has a method to return a DisasterBackupInterface.
// A group's client should implement this interface.
type DisasterBackupsGetter interface {
	DisasterBackups(namespace string) DisasterBackupInterface
}

// DisasterBackupInterface has methods to work with DisasterBackup resources.
type DisasterBackupInterface interface {
	Create(ctx context.Context, disasterBackup *disasterv1.DisasterBackup, opts metav1.CreateOptions) (*disasterv1.DisasterBackup, error)
	Update(ctx context.Context, disasterBackup *disasterv1.DisasterBackup, opts metav1.UpdateOptions) (*disasterv1.DisasterBackup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, disasterBackup *disasterv1.DisasterBackup, opts metav1.UpdateOptions) (*disasterv1.DisasterBackup, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*disasterv1.DisasterBackup, error)
	List(ctx context.Context, opts metav1.ListOptions) (*disasterv1.DisasterBackupList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *disasterv1.DisasterBackup, err error)
	DisasterBackupExpansion
}

// disasterBackups implements DisasterBackupInterface
type disasterBackups struct {
	*gentype.ClientWithList[*disasterv1.DisasterBackup, *disasterv1.DisasterBackupList]
}

// newDisasterBackups returns a DisasterBackups
func newDisasterBackups(c *DisasterV1Client, namespace string) *disasterBackups {
	return &disasterBackups{
		gentype.NewClientWithList[*disasterv1.DisasterBackup, *disasterv1.DisasterBackupList](
			"disasterbackups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *disasterv1.DisasterBackup { return &disasterv1.DisasterBackup{} },
			func() *disasterv1.DisasterBackupList { return &disasterv1.DisasterBackupList{} },
		),
	}
}
