/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	scheme "github.com/softcdata/testudo-operator/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DisasterPoliciesGetter has a method to return a DisasterPolicyInterface.
// A group's client should implement this interface.
type DisasterPoliciesGetter interface {
	DisasterPolicies(namespace string) DisasterPolicyInterface
}

// DisasterPolicyInterface has methods to work with DisasterPolicy resources.
type DisasterPolicyInterface interface {
	Create(ctx context.Context, disasterPolicy *disasterv1.DisasterPolicy, opts metav1.CreateOptions) (*disasterv1.DisasterPolicy, error)
	Update(ctx context.Context, disasterPolicy *disasterv1.DisasterPolicy, opts metav1.UpdateOptions) (*disasterv1.DisasterPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, disasterPolicy *disasterv1.DisasterPolicy, opts metav1.UpdateOptions) (*disasterv1.DisasterPolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*disasterv1.DisasterPolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*disasterv1.DisasterPolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *disasterv1.DisasterPolicy, err error)
	DisasterPolicyExpansion
}

// disasterPolicies implements DisasterPolicyInterface
type disasterPolicies struct {
	*gentype.ClientWithList[*disasterv1.DisasterPolicy, *disasterv1.DisasterPolicyList]
}

// newDisasterPolicies returns a DisasterPolicies
func newDisasterPolicies(c *DisasterV1Client, namespace string) *disasterPolicies {
	return &disasterPolicies{
		gentype.NewClientWithList[*disasterv1.DisasterPolicy, *disasterv1.DisasterPolicyList](
			"disasterpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *disasterv1.DisasterPolicy { return &disasterv1.DisasterPolicy{} },
			func() *disasterv1.DisasterPolicyList { return &disasterv1.DisasterPolicyList{} },
		),
	}
}
