/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	disasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	scheme "github.com/softcdata/testudo-operator/pkg/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type DisasterV1Interface interface {
	RESTClient() rest.Interface
	AppBackupsGetter
	AppRestoresGetter
	BackupPoliciesGetter
	BackupRestoreStatisticsesGetter
	ClustersGetter
	DataSyncsGetter
	DisasterBackupsGetter
	DisasterConfigsGetter
	DisasterDrillsGetter
	DisasterGroupsGetter
	DisasterInstancesGetter
	DisasterJobsGetter
	DisasterOperationsGetter
	DisasterPoliciesGetter
	ResourceSyncsGetter
	StorageRepositoriesGetter
}

// DisasterV1Client is used to interact with features provided by the disaster group.
type DisasterV1Client struct {
	restClient rest.Interface
}

func (c *DisasterV1Client) AppBackups(namespace string) AppBackupInterface {
	return newAppBackups(c, namespace)
}

func (c *DisasterV1Client) AppRestores(namespace string) AppRestoreInterface {
	return newAppRestores(c, namespace)
}

func (c *DisasterV1Client) BackupPolicies(namespace string) BackupPolicyInterface {
	return newBackupPolicies(c, namespace)
}

func (c *DisasterV1Client) BackupRestoreStatisticses(namespace string) BackupRestoreStatisticsInterface {
	return newBackupRestoreStatisticses(c, namespace)
}

func (c *DisasterV1Client) Clusters() ClusterInterface {
	return newClusters(c)
}

func (c *DisasterV1Client) DataSyncs(namespace string) DataSyncInterface {
	return newDataSyncs(c, namespace)
}

func (c *DisasterV1Client) DisasterBackups(namespace string) DisasterBackupInterface {
	return newDisasterBackups(c, namespace)
}

func (c *DisasterV1Client) DisasterConfigs() DisasterConfigInterface {
	return newDisasterConfigs(c)
}

func (c *DisasterV1Client) DisasterDrills(namespace string) DisasterDrillInterface {
	return newDisasterDrills(c, namespace)
}

func (c *DisasterV1Client) DisasterGroups(namespace string) DisasterGroupInterface {
	return newDisasterGroups(c, namespace)
}

func (c *DisasterV1Client) DisasterInstances(namespace string) DisasterInstanceInterface {
	return newDisasterInstances(c, namespace)
}

func (c *DisasterV1Client) DisasterJobs(namespace string) DisasterJobInterface {
	return newDisasterJobs(c, namespace)
}

func (c *DisasterV1Client) DisasterOperations(namespace string) DisasterOperationInterface {
	return newDisasterOperations(c, namespace)
}

func (c *DisasterV1Client) DisasterPolicies(namespace string) DisasterPolicyInterface {
	return newDisasterPolicies(c, namespace)
}

func (c *DisasterV1Client) ResourceSyncs(namespace string) ResourceSyncInterface {
	return newResourceSyncs(c, namespace)
}

func (c *DisasterV1Client) StorageRepositories(namespace string) StorageRepositoryInterface {
	return newStorageRepositories(c, namespace)
}

// NewForConfig creates a new DisasterV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*DisasterV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new DisasterV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*DisasterV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &DisasterV1Client{client}, nil
}

// NewForConfigOrDie creates a new DisasterV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DisasterV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DisasterV1Client for the given RESTClient.
func New(c rest.Interface) *DisasterV1Client {
	return &DisasterV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := disasterv1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DisasterV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
