/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisdisasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	versioned "github.com/softcdata/testudo-operator/pkg/clientset/versioned"
	internalinterfaces "github.com/softcdata/testudo-operator/pkg/informers/externalversions/internalinterfaces"
	disasterv1 "github.com/softcdata/testudo-operator/pkg/listers/disaster/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AppRestoreInformer provides access to a shared informer and lister for
// AppRestores.
type AppRestoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() disasterv1.AppRestoreLister
}

type appRestoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAppRestoreInformer constructs a new informer for AppRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAppRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAppRestoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAppRestoreInformer constructs a new informer for AppRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAppRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().AppRestores(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().AppRestores(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().AppRestores(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().AppRestores(namespace).Watch(ctx, options)
			},
		},
		&apisdisasterv1.AppRestore{},
		resyncPeriod,
		indexers,
	)
}

func (f *appRestoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAppRestoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *appRestoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdisasterv1.AppRestore{}, f.defaultInformer)
}

func (f *appRestoreInformer) Lister() disasterv1.AppRestoreLister {
	return disasterv1.NewAppRestoreLister(f.Informer().GetIndexer())
}
