/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisdisasterv1 "github.com/softcdata/testudo-operator/pkg/apis/disaster/v1"
	versioned "github.com/softcdata/testudo-operator/pkg/clientset/versioned"
	internalinterfaces "github.com/softcdata/testudo-operator/pkg/informers/externalversions/internalinterfaces"
	disasterv1 "github.com/softcdata/testudo-operator/pkg/listers/disaster/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DisasterBackupInformer provides access to a shared informer and lister for
// DisasterBackups.
type DisasterBackupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() disasterv1.DisasterBackupLister
}

type disasterBackupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDisasterBackupInformer constructs a new informer for DisasterBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDisasterBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDisasterBackupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDisasterBackupInformer constructs a new informer for DisasterBackup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDisasterBackupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().DisasterBackups(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().DisasterBackups(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().DisasterBackups(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DisasterV1().DisasterBackups(namespace).Watch(ctx, options)
			},
		},
		&apisdisasterv1.DisasterBackup{},
		resyncPeriod,
		indexers,
	)
}

func (f *disasterBackupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDisasterBackupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *disasterBackupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdisasterv1.DisasterBackup{}, f.defaultInformer)
}

func (f *disasterBackupInformer) Lister() disasterv1.DisasterBackupLister {
	return disasterv1.NewDisasterBackupLister(f.Informer().GetIndexer())
}
