/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/softcdata/testudo-operator/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AppBackups returns a AppBackupInformer.
	AppBackups() AppBackupInformer
	// AppRestores returns a AppRestoreInformer.
	AppRestores() AppRestoreInformer
	// BackupPolicies returns a BackupPolicyInformer.
	BackupPolicies() BackupPolicyInformer
	// BackupRestoreStatisticses returns a BackupRestoreStatisticsInformer.
	BackupRestoreStatisticses() BackupRestoreStatisticsInformer
	// Clusters returns a ClusterInformer.
	Clusters() ClusterInformer
	// DataSyncs returns a DataSyncInformer.
	DataSyncs() DataSyncInformer
	// DisasterBackups returns a DisasterBackupInformer.
	DisasterBackups() DisasterBackupInformer
	// DisasterConfigs returns a DisasterConfigInformer.
	DisasterConfigs() DisasterConfigInformer
	// DisasterDrills returns a DisasterDrillInformer.
	DisasterDrills() DisasterDrillInformer
	// DisasterGroups returns a DisasterGroupInformer.
	DisasterGroups() DisasterGroupInformer
	// DisasterInstances returns a DisasterInstanceInformer.
	DisasterInstances() DisasterInstanceInformer
	// DisasterJobs returns a DisasterJobInformer.
	DisasterJobs() DisasterJobInformer
	// DisasterOperations returns a DisasterOperationInformer.
	DisasterOperations() DisasterOperationInformer
	// DisasterPolicies returns a DisasterPolicyInformer.
	DisasterPolicies() DisasterPolicyInformer
	// ResourceSyncs returns a ResourceSyncInformer.
	ResourceSyncs() ResourceSyncInformer
	// StorageRepositories returns a StorageRepositoryInformer.
	StorageRepositories() StorageRepositoryInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AppBackups returns a AppBackupInformer.
func (v *version) AppBackups() AppBackupInformer {
	return &appBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AppRestores returns a AppRestoreInformer.
func (v *version) AppRestores() AppRestoreInformer {
	return &appRestoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BackupPolicies returns a BackupPolicyInformer.
func (v *version) BackupPolicies() BackupPolicyInformer {
	return &backupPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BackupRestoreStatisticses returns a BackupRestoreStatisticsInformer.
func (v *version) BackupRestoreStatisticses() BackupRestoreStatisticsInformer {
	return &backupRestoreStatisticsInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Clusters returns a ClusterInformer.
func (v *version) Clusters() ClusterInformer {
	return &clusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DataSyncs returns a DataSyncInformer.
func (v *version) DataSyncs() DataSyncInformer {
	return &dataSyncInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterBackups returns a DisasterBackupInformer.
func (v *version) DisasterBackups() DisasterBackupInformer {
	return &disasterBackupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterConfigs returns a DisasterConfigInformer.
func (v *version) DisasterConfigs() DisasterConfigInformer {
	return &disasterConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DisasterDrills returns a DisasterDrillInformer.
func (v *version) DisasterDrills() DisasterDrillInformer {
	return &disasterDrillInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterGroups returns a DisasterGroupInformer.
func (v *version) DisasterGroups() DisasterGroupInformer {
	return &disasterGroupInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterInstances returns a DisasterInstanceInformer.
func (v *version) DisasterInstances() DisasterInstanceInformer {
	return &disasterInstanceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterJobs returns a DisasterJobInformer.
func (v *version) DisasterJobs() DisasterJobInformer {
	return &disasterJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterOperations returns a DisasterOperationInformer.
func (v *version) DisasterOperations() DisasterOperationInformer {
	return &disasterOperationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DisasterPolicies returns a DisasterPolicyInformer.
func (v *version) DisasterPolicies() DisasterPolicyInformer {
	return &disasterPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ResourceSyncs returns a ResourceSyncInformer.
func (v *version) ResourceSyncs() ResourceSyncInformer {
	return &resourceSyncInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// StorageRepositories returns a StorageRepositoryInformer.
func (v *version) StorageRepositories() StorageRepositoryInformer {
	return &storageRepositoryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
